### ISSUE TITLE
Update link to raw file for wget

### ISSUE THREAD

**Issue by mvhconsult** [jorgedlcruz/zimbra-grafana#1]
The link at https://wiki.zimbra.com/wiki/Monitoring_Zimbra_Collaboration_-_InfluxDB,_Telegraf_and_Grafana
pointing to the github repository will return an HTML page
Use the raw link for a working download.

https://raw.githubusercontent.com/jorgedlcruz/zimbra-grafana/master/zimbra_pflogsumm.pl

**Comment by jorgedlcruz** [comment]
Fixed it! Thanks!
