### ISSUE TITLE
Add step to doc: make pl executable

### ISSUE THREAD

**Issue by mvhconsult** [jorgedlcruz/zimbra-grafana#3]
Sorry for being a pain.

https://wiki.zimbra.com/wiki/Monitoring_Zimbra_Collaboration_-_InfluxDB,_Telegraf_and_Grafana

After downloading the file, do not forget to make it executable 
`chmod +rwxr+xr+x zimbra_pflogsumm.pl`

**Comment by jorgedlcruz** [comment]
Fixed it! Thanks!
