### ISSUE TITLE
 E! Error in plugin [inputs.exec]:  invalid number

### ISSUE THREAD

**Issue by mvhconsult** [jorgedlcruz/zimbra-grafana#4]
After importing some accounts into this recent server, I am getting this error. Config file is 100% as described in the setup.
Grafana display shows no data for the Zimbra items (tot emails received etc), except for version number.

Running the test for zimbra_pflogsumm.pl returns no errors, and valid numbers:
` sudo -u telegraf /opt/zimbra/common/bin/zimbra_pflogsumm.pl /var/log/zimbra.log`
zimbra-stats received=160
zimbra-stats delivered=479
zimbra-stats forwarded=0
zimbra-stats deferred=0
zimbra-stats bounced=0
zimbra-stats rejected=54
zimbra-stats reject_warnings=0
zimbra-stats held=0
zimbra-stats discarded=0
zimbra-stats bytes_received=144996
zimbra-stats bytes_delivered=673k
zimbra-stats senders=2
zimbra-stats sending_hosts_domains=1
zimbra-stats recipients=2
zimbra-stats recipient_hosts_domains=2

Any idea?

**Comment by jorgedlcruz** [comment]
Hello, do you have anything in the telegraf log?

**Comment by mvhconsult** [comment]
Yes, loads of 
E! Error in plugin [inputs.exec]: invalid number

**Comment by mvhconsult** [comment]
ok, turned out to be a problem with IPv6 and virtual domains. The patches provided by users are still not implemented, so had to manually adjust the templates. 
That now works, and meanwhile decided to go to 8.8.
There with this setup (and IPv6 patched) no problems.

Closing.
